### ISSUE TITLE
Break free fights down into individually click-able links

### ISSUE THREAD

**Issue by JamesDowney** [Loathing-Associates-Scripting-Society/TourGuide#16]
Right now, clicking anywhere in the free fight tile will always direct you to the current top level resource, rather than allowing you to click on whichever specific free fight you'd like to utilize.

**Comment by docrostov** [comment]
i waited longer to close this one because i thought maybe there was a clever way to do it but i couldn't solve it. it is a good idea but i just could not figure it out. sorry doggs.
