### ISSUE TITLE
Allow multiple images per tile

### ISSUE THREAD

**Issue by JamesDowney** [Loathing-Associates-Scripting-Society/TourGuide#26]
Right now only one image can be shown in each tile, I'd like to be able to use more than one image per tile for things like free fight sources and crystal ball predicitons.

**Comment by docrostov** [comment]
i think this was a good idea but after digging in i really have no idea how you would add this level of extensibility to this code and at this point i am OK with saying this is out of scope given the volunteers available for tourguide.
