### ISSUE TITLE
Support user preferences and multiple configurations

### ISSUE THREAD

**Issue by JamesDowney** [Loathing-Associates-Scripting-Society/TourGuide#27]
Right now, there's only one base configuration for tourguide and a user can't configure it via preferences. I'd like to eventually support both of these things.

**Comment by docrostov** [comment]
this is a good issue, but i think this is going to take a more substantial rework than we have the volunteers for, and yorick progress is probably a better way to hit this goal (as yorick being developed from the ground up makes it much, much easier to add fungibility and configurability than the massive codebase we've got for tourguide.) closing.
