### ISSUE TITLE
Machine Elf Tile Logic

### ISSUE THREAD

**Issue by Tokoeka** [Loathing-Associates-Scripting-Society/TourGuide#3]
Logic for Machine Elf Tile Logic does not appear to use either of Mafia preferences `encountersUntilDMTChoice` or `lastDMTDuplication`, rather appears to be relying on "does the adventure appear in your noncombat queue".

This feels less prefereable to me, wanted to make sure I wasn't barking up the wrong tree by getting other peoples opinion before attempting to do anythign about it.

**Comment by docrostov** [comment]
i realize this is nearly a year old at this point but if you want to fix this up we would be happy to take it. i agree that using the prefs is preferable here, i think TES & i have just largely avoided touching ezan code directly.

**Comment by docrostov** [comment]
![image](https://user-images.githubusercontent.com/8014761/183478835-f2ce9071-8e92-48ac-bc9a-a244b3f7e036.png)
okay to fix this tile i need to figure out how these stupid prefs work but it should be pretty easy when i'm on a computer with mafia

**Comment by uthuluc** [comment]
will be resolved in the next update

**Comment by docrostov** [comment]
finally blessedly addressed in #82
