### ISSUE TITLE
Location name changes post r26631

### ISSUE THREAD

**Issue by magus-prime** [Loathing-Associates-Scripting-Society/TourGuide#64]
On loading TourGuide prints the following to the gCLI and the main window never loads.

Bad location value: "Frat House In Disguise" (relay_TourGuide.ash, line 38570, char 83 to char 105)
Bad location value: "Hippy Camp In Disguise" (relay_TourGuide.ash, line 38572, char 84 to char 106)
Bad location value: "Frat House In Disguise" (relay_TourGuide.ash, line 38570, char 83 to char 105)
Bad location value: "Hippy Camp In Disguise" (relay_TourGuide.ash, line 38572, char 84 to char 106)

See https://kolmafia.us/threads/ash-location_accessible-function.27836/ for details.

**Comment by docrostov** [comment]
this has been fixed in #62 -- thank you! :-)
